export const testUsers = [{
  id: '65ca8479345675bfe',
  name: 'Joan Huang',
  deleted: false,
  salutationName: null,
  firstName: 'Joan',
  lastName: 'Huang',
  title: null,
  description: 'Online Resume: https://jojoxo.web.app/index.html',
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-12 20:50:01',
  modifiedAt: '2024-02-21 21:32:41',
  hasPortalUser: false,
  skills: [
    'css',        'figma',
    'frontend',   'html',
    'javascript', 'laravel',
    'php',        'react',
    'sql',        'vue',
    'wordpress'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65ca82f9a6fd2f83d',
  name: 'Jim Lan',
  deleted: false,
  salutationName: null,
  firstName: 'Jim',
  lastName: 'Lan',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-12 20:43:37',
  modifiedAt: '2024-02-21 21:33:07',
  hasPortalUser: false,
  skills: [ 'firmware dev', 'tr/tx', 'wfa tgn/tgac', 'wifi' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65ca81e23b79af177',
  name: 'Richard Lee',
  deleted: false,
  salutationName: null,
  firstName: 'Richard',
  lastName: 'Lee',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-12 20:38:58',
  modifiedAt: '2024-02-21 21:34:02',
  hasPortalUser: false,
  skills: [ 'AI', 'android', 'java', 'machine learning', 'php', 'python' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65ca7faa8c089c70c',
  name: 'Wilson Kao',
  deleted: false,
  salutationName: null,
  firstName: 'Wilson',
  lastName: 'Kao',
  title: null,
  description: 'Updated resume link: https://www.cakeresume.com/s--H1Fps82FJOrXy5l6AzKibw--/wilson-kao-a402d7',
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-12 20:29:30',
  modifiedAt: '2024-02-21 21:35:34',
  hasPortalUser: false,
  skills: [
    'axios',       'css',
    'firebase',    'frontend',
    'git',         'html',
    'javascript',  'node',
    'pinia',       'python',
    'restful api', 'tailwind',
    'typescript',  'vue'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65c57415528ed25b3',
  name: 'Henry Chang',
  deleted: false,
  salutationName: null,
  firstName: 'Henry',
  lastName: 'Chang',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-09 00:38:45',
  modifiedAt: '2024-02-26 03:32:27',
  hasPortalUser: false,
  skills: [ 'backend', 'python' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65c2a4f7b96783eaf',
  name: 'Paul Yu',
  deleted: false,
  salutationName: null,
  firstName: 'Paul',
  lastName: 'Yu',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-06 21:30:31',
  modifiedAt: '2024-02-21 21:40:26',
  hasPortalUser: false,
  skills: [
    'circom',
    'cryptocurrency',
    'fullstack',
    'javascript',
    'python',
    'react',
    'solidity',
    'sql',
    'typescript',
    'web3'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65c2a39ab3ea28a9d',
  name: 'Zachary Fogg',
  deleted: false,
  salutationName: null,
  firstName: 'Zachary',
  lastName: 'Fogg',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-06 21:24:42',
  modifiedAt: '2024-04-03 06:41:59',
  hasPortalUser: false,
  skills: [
    '.net',       'aws',
    'c',          'Cryptocurrency',
    'docker',     'fullstack',
    'javascript', 'kubernetes',
    'linux',      'node',
    'php',        'python',
    'react',      'redis',
    'sql',        'tailwind',
    'unix',       'web3',
    'wordpress'
  ],
  type: 'Candidate / Member',
  publicDescription: 'Specializing in frontend web, devops/infrastructure, and blockchain applications, Zach has built applications for many different types of startups and companies over the past decade. He also has experience building games and bots. He is comfortable in Javascript, Typescript, Python, C, and Solidity.\n' +
    '\n',
  publicLink: 'https://zfo.gg/',
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6582cb8dccdf179ca',
  modifiedByName: 'Caleb Rogers',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: '660cfa34896d5a8c4',
  publicPhotoName: 'zacharyfogg.png'
}
{
  id: '65c2a1ee2d913d20f',
  name: 'Jeremy Cheng',
  deleted: false,
  salutationName: null,
  firstName: 'Jeremy',
  lastName: 'Cheng',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-02-06 21:17:34',
  modifiedAt: '2024-02-21 21:42:10',
  hasPortalUser: false,
  skills: [
    'backend', 'docker',
    'java',    'kafka',
    'laravel', 'python',
    'rust',    'sql'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65b824e9e79158cdf',
  name: 'Tony Yang',
  deleted: false,
  salutationName: null,
  firstName: 'Tony',
  lastName: 'Yang',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-29 22:21:29',
  modifiedAt: '2024-02-21 21:42:58',
  hasPortalUser: false,
  skills: [
    'firebase',  'flask',
    'fullstack', 'javascript',
    'nextjs',    'nuxtjs',
    'python',    'run',
    'sql'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65b5ac38adfb33951',
  name: 'Jack Huang',
  deleted: false,
  salutationName: null,
  firstName: 'Jack',
  lastName: 'Huang',
  title: null,
  description: 'Resume: https://docs.google.com/document/d/e/2PACX-1vSrUPH35yF3nd5XkXWy3D63C5Z5qgxSXdoUHpgTtoCpv-yXZVYl-O3UOo8BbJo-er8zLiE5zmkboc3f/pub?urp=gmail_link',
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-28 01:22:00',
  modifiedAt: '2024-02-28 20:39:03',
  hasPortalUser: false,
  skills: [
    'android', 'backend',
    'c',       'c#',
    'c++',     'docker',
    'gcp',     'git',
    'java',    'jenkins',
    'linux',   'python',
    'sse'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65b284ff5ee23c61d',
  name: 'Ching-Huan Li',
  deleted: false,
  salutationName: null,
  firstName: 'Ching-Huan',
  lastName: 'Li',
  title: null,
  description: 'LinkedIn: https://www.linkedin.com/in/ching-huan-li-7bb9a128/',
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-25 15:57:51',
  modifiedAt: '2024-02-28 22:30:26',
  hasPortalUser: false,
  skills: [
    'aws',         'backend',
    'c',           'docker',
    'dynamo',      'git',
    'go',          'grpc',
    'kafka',       'kubernetes',
    'python',      'redis',
    'restful api', 'rust',
    'typescript'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65b2751bb05d97c50',
  name: 'Chia-Yu Chen',
  deleted: false,
  salutationName: null,
  firstName: 'Chia-Yu',
  lastName: 'Chen',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-25 14:50:03',
  modifiedAt: '2024-02-21 21:50:33',
  hasPortalUser: false,
  skills: [ 'css', 'designer', 'figma', 'html', 'ux/ui' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65b079e3536564209',
  name: 'Dennis Ordanov',
  deleted: false,
  salutationName: null,
  firstName: 'Dennis',
  lastName: 'Ordanov',
  title: null,
  description: 'https://www.linkedin.com/in/daodennis/',
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-24 02:45:55',
  modifiedAt: '2024-02-21 21:53:18',
  hasPortalUser: false,
  skills: [
    'aws',        'devops',
    'docker',     'elasticsearch',
    'go',         'infosec',
    'java',       'kafka',
    'kubernetes', 'linux',
    'python',     'terraform'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6582cb8dccdf179ca',
  createdByName: 'Caleb Rogers',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65b00db4a0d5ace87',
  name: 'Simone Massenzio',
  deleted: false,
  salutationName: null,
  firstName: 'Simone',
  lastName: 'Massenzio',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-23 19:04:20',
  modifiedAt: '2024-02-21 21:56:00',
  hasPortalUser: false,
  skills: [ 'backend', 'google cloud', 'java', 'python', 'spring boot', 'sql' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65ad6f68ea79e3183',
  name: 'Kai-Da (Charles) Hsieh',
  deleted: false,
  salutationName: null,
  firstName: 'Kai-Da (Charles)',
  lastName: 'Hsieh',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-21 19:24:24',
  modifiedAt: '2024-02-21 21:56:35',
  hasPortalUser: false,
  skills: [ 'combine', 'git', 'ios', 'mvvm-c', 'swift', 'uikit' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65ad6d38d37f71446',
  name: 'Cheng-Yi Shih',
  deleted: false,
  salutationName: null,
  firstName: 'Cheng-Yi',
  lastName: 'Shih',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-21 19:15:04',
  modifiedAt: '2024-02-21 21:59:05',
  hasPortalUser: false,
  skills: [
    'backend',
    'cryptocurrency',
    'data scraping',
    'java',
    'node',
    'spring boot'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a96898a6bee1f00',
  name: 'Hui-Ru Hu',
  deleted: false,
  salutationName: null,
  firstName: 'Hui-Ru',
  lastName: 'Hu',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-18 18:06:16',
  modifiedAt: '2024-02-21 22:00:32',
  hasPortalUser: false,
  skills: [
    'css',
    'django',
    'flask',
    'fullstack',
    'html',
    'javascript',
    'python'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a9671fbc9eb4d67',
  name: 'Jess Wang',
  deleted: false,
  salutationName: null,
  firstName: 'Jess',
  lastName: 'Wang',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-18 17:59:59',
  modifiedAt: '2024-02-21 22:01:43',
  hasPortalUser: false,
  skills: [
    'aws',    'backend',
    'docker', 'flutter',
    'kafka',  'mongo',
    'php',    'react',
    'redis',  'sql'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a7f488a512c13c9',
  name: 'YuChi Chien',
  deleted: false,
  salutationName: null,
  firstName: 'YuChi',
  lastName: 'Chien',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-17 15:38:48',
  modifiedAt: '2024-02-21 22:03:44',
  hasPortalUser: false,
  skills: [
    'aws',         'css',
    'frontend',    'fullstack',
    'git',         'html',
    'javascript',  'nextjs',
    'python',      'react',
    'restful api', 'sql'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a7f2fd211473f04',
  name: 'David Chien',
  deleted: false,
  salutationName: null,
  firstName: 'David',
  lastName: 'Chien',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-17 15:32:13',
  modifiedAt: '2024-02-21 22:04:43',
  hasPortalUser: false,
  skills: [
    'c#',     'css',
    'docker', 'fullstack',
    'html',   'javascript',
    'rails',  'ruby',
    'sql'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a6db42c7fee65d4',
  name: 'Ian Lin',
  deleted: false,
  salutationName: null,
  firstName: 'Ian',
  lastName: 'Lin',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-16 19:38:42',
  modifiedAt: '2024-02-21 22:05:40',
  hasPortalUser: false,
  skills: [
    'c#',         'css',
    'fullstack',  'html',
    'java',       'javascript',
    'python',     'sql',
    'typescript'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a6bfaa2cb12c47f',
  name: 'Daniel Tong',
  deleted: false,
  salutationName: null,
  firstName: 'Daniel',
  lastName: 'Tong',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-16 17:40:58',
  modifiedAt: '2024-02-21 22:12:28',
  hasPortalUser: false,
  skills: [ 'AEM', 'css', 'html', 'javascript', 'python' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a6b7682799e9a1c',
  name: 'Tristan Wang',
  deleted: false,
  salutationName: null,
  firstName: 'Tristan',
  lastName: 'Wang',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-16 17:05:44',
  modifiedAt: '2024-02-21 22:45:13',
  hasPortalUser: false,
  skills: [
    'c',          'c++',
    'css',        'express',
    'html',       'java',
    'javascript', 'mongo',
    'node',       'python',
    'react'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a6b62400e7d0079',
  name: 'Michael Wu',
  deleted: false,
  salutationName: null,
  firstName: 'Michael',
  lastName: 'Wu',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-16 17:00:20',
  modifiedAt: '2024-04-03 06:40:51',
  hasPortalUser: false,
  skills: [
    'c',          'c++',
    'css',        'fullstack',
    'html',       'java',
    'javascript', 'matlab',
    'pearl',      'php',
    'python',     'qt',
    'rails',      'react',
    'redis',      'ruby',
    'scala',      'sql',
    'typescript'
  ],
  type: 'Candidate / Member',
  publicDescription: 'Software engineer and founder with over 12 years of experience at Pixelapse (YC W12), Dropbox, Gem, and Stripe. Backend and desktop development experience, proficiency with Python, Ruby, Javascript, Java, Scala, C and more.\n' +
    '\n',
  publicLink: 'http://linkedin.com/in/wumichaelm/',
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6582cb8dccdf179ca',
  modifiedByName: 'Caleb Rogers',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: '660cf9f132257343e',
  publicPhotoName: 'michaelwu.jpg'
}
{
  id: '65a5ff23d793def6c',
  name: 'Joseph Lin',
  deleted: false,
  salutationName: null,
  firstName: 'Joseph',
  lastName: 'Lin',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-16 03:59:31',
  modifiedAt: '2024-02-21 22:20:22',
  hasPortalUser: false,
  skills: [ 'backend', 'c', 'java', 'machine learning', 'python', 'rust' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a5fbb5678990802',
  name: 'JuYin Chao',
  deleted: false,
  salutationName: null,
  firstName: 'JuYin',
  lastName: 'Chao',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-16 03:44:53',
  modifiedAt: '2024-02-21 22:21:58',
  hasPortalUser: false,
  skills: [ 'fullstack', 'java', 'python', 'sql', 'vue.js' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '65a5d89c1b887d3f6',
  createdByName: 'Nestor Morales',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65a0f4bf95cd6e2a9',
  name: 'Chia-Hung Lin',
  deleted: false,
  salutationName: null,
  firstName: 'Chia-Hung',
  lastName: 'Lin',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-12 08:13:51',
  modifiedAt: '2024-02-21 22:23:15',
  hasPortalUser: false,
  skills: [
    'aws',
    'backend',
    'firebase',
    'google cloud',
    'java',
    'mongo',
    'python',
    'sql'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6582cb8dccdf179ca',
  createdByName: 'Caleb Rogers',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '659836a026ca60354',
  name: 'Alex Wang',
  deleted: false,
  salutationName: null,
  firstName: 'Alex',
  lastName: 'Wang',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-05 17:04:32',
  modifiedAt: '2024-02-21 22:33:45',
  hasPortalUser: false,
  skills: [
    '.net',         'aws',
    'c',            'c#',
    'css',          'git',
    'google cloud', 'ios',
    'javascript',   'laravel',
    'linux',        'oracle',
    'php',          'sql',
    'swift'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '6598061b1fd20e7dd',
  name: 'Linion Lin',
  deleted: false,
  salutationName: null,
  firstName: 'Linion',
  lastName: 'Lin',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-05 13:37:31',
  modifiedAt: '2024-02-21 22:34:09',
  hasPortalUser: false,
  skills: [
    '.net',
    'c#',
    'data scraping',
    'fastapi',
    'fullstack',
    'angular',
    'javascript',
    'python',
    'restful api',
    'vue'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65976dae8f3bd90fb',
  name: 'Wilson Hung',
  deleted: false,
  salutationName: null,
  firstName: 'Wilson',
  lastName: 'Hung',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-05 02:47:10',
  modifiedAt: '2024-02-21 22:33:07',
  hasPortalUser: false,
  skills: [
    'aws',              'c',
    'c++',              'docker',
    'dynamo',           'express',
    'flask',            'fullstack',
    'java',             'javascript',
    'machine learning', 'mongo',
    'python',           'pytorch',
    'react',            'redis',
    'ros',              'typescript'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65976be69050ae48e',
  name: 'Kuan Ru Chiao',
  deleted: false,
  salutationName: null,
  firstName: 'Kuan Ru',
  lastName: 'Chiao',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-05 02:39:34',
  modifiedAt: '2024-02-26 19:59:29',
  hasPortalUser: false,
  skills: [
    'AI',              'aws',
    'backend',         'c++',
    'computer vision', 'docker',
    'git',             'latex',
    'linux',           'machine learning',
    'matlab',          'numpy',
    'pandas',          'python',
    'pytorch',         'qskit',
    'xgboost'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65976474524ac4c70',
  name: 'Rock Lin',
  deleted: false,
  salutationName: null,
  firstName: 'Rock',
  lastName: 'Lin',
  title: null,
  description: 'Entry-level engineer, learned Java, no professional experience yet',
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2024-01-05 02:07:48',
  modifiedAt: '2024-02-21 22:35:30',
  hasPortalUser: false,
  skills: [ 'java' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '658d888c8e55ba7c3',
  name: 'Albert Chang',
  deleted: false,
  salutationName: null,
  firstName: 'Albert',
  lastName: 'Chang',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2023-12-28 14:39:08',
  modifiedAt: '2024-02-21 22:32:14',
  hasPortalUser: false,
  skills: [
    'android',  'backend',
    'c',        'c++',
    'java',     'linux',
    'miracast', 'python'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '658c02e766c590368',
  name: 'Leni Kadali',
  deleted: false,
  salutationName: null,
  firstName: 'Leni',
  lastName: 'Kadali',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2023-12-27 10:56:39',
  modifiedAt: '2024-02-21 22:36:08',
  hasPortalUser: false,
  skills: [ 'backend', 'django', 'python', 'rails', 'ruby' ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '658302e5c18cfb335',
  createdByName: 'Leni Kadali',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '6583d45170f017075',
  name: 'Thomas Breier',
  deleted: false,
  salutationName: null,
  firstName: 'Thomas',
  lastName: 'Breier',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2023-12-21 05:59:45',
  modifiedAt: '2024-02-21 22:38:39',
  hasPortalUser: false,
  skills: [
    'aws',
    'css',
    'html',
    'javascript',
    'python',
    'rails',
    'ruby',
    'sql'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6582cb8dccdf179ca',
  createdByName: 'Caleb Rogers',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '6583aa568c74c82e8',
  name: 'Adrian Wu',
  deleted: false,
  salutationName: null,
  firstName: 'Adrian',
  lastName: 'Wu',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2023-12-21 03:00:38',
  modifiedAt: '2024-02-21 22:40:27',
  hasPortalUser: false,
  skills: [
    '.net',        'c#',
    'fullstack',   'go',
    'javascript',  'python',
    'spring boot', 'sql',
    'vue'
  ],
  type: 'Candidate / Member',
  publicDescription: null,
  publicLink: null,
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6582cb8dccdf179ca',
  createdByName: 'Caleb Rogers',
  modifiedById: '6583041ddb944e569',
  modifiedByName: 'Sam Simonds',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '65830b0bde8ec3d3f',
  name: 'Sam Simonds',
  deleted: false,
  salutationName: null,
  firstName: 'Sam',
  lastName: 'Simonds',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2023-12-20 15:40:59',
  modifiedAt: '2024-04-03 06:41:24',
  hasPortalUser: false,
  skills: [
    'css',        'frontend',
    'graphql',    'html',
    'javascript', 'nextjs',
    'react',      'sql',
    'tailwind',   'typescript'
  ],
  type: 'Candidate / Member',
  publicDescription: "Software engineer with a strong foundation in applications leveraging TypeScript / Next.js, JavaScript, HTML and CSS. He's built web applications for start ups, healthcare organizations, and non-profits around the world.\n" +
    '\n',
  publicLink: 'https://www.linkedin.com/in/sam-simonds-485159b0/',
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6583041ddb944e569',
  createdByName: 'Sam Simonds',
  modifiedById: '6582cb8dccdf179ca',
  modifiedByName: 'Caleb Rogers',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: null,
  publicPhotoName: null
}
{
  id: '6583084fa934ec4ed',
  name: 'Caleb Rogers',
  deleted: false,
  salutationName: null,
  firstName: 'Caleb',
  lastName: 'Rogers',
  title: null,
  description: null,
  doNotCall: false,
  accountIsInactive: null,
  accountType: null,
  createdAt: '2023-12-20 15:29:19',
  modifiedAt: '2024-04-03 06:39:23',
  hasPortalUser: false,
  skills: [
    'aws',        'backend',
    'devops',     'django',
    'fastapi',    'frontend',
    'fullstack',  'google cloud',
    'graphql',    'javascript',
    'mongo',      'nextjs',
    'node',       'python',
    'react',      'sql',
    'typescript'
  ],
  type: 'Candidate / Member',
  publicDescription: 'Software engineering lead and founder with eight years of experience building software in the Bay Area for startups such as Electric Imp, Curative, and Cofactr (YC W22), and enterprise companies such as WPP, Ubisoft, and Google. ',
  publicLink: 'https://www.calebjay.com/',
  middleName: null,
  accountId: null,
  accountName: null,
  campaignId: null,
  campaignName: null,
  createdById: '6582cb8dccdf179ca',
  createdByName: 'Caleb Rogers',
  modifiedById: '6582cb8dccdf179ca',
  modifiedByName: 'Caleb Rogers',
  assignedUserId: null,
  assignedUserName: null,
  portalUserId: null,
  portalUserName: null,
  originalLeadId: null,
  originalLeadName: null,
  publicPhotoId: '660cf9221a4e98c60',
  publicPhotoName: 'caleb.JPG'
};
