export const testUsers = [
  {
    id: "65ca8479345675bfe",
    name: "Joan Huang",
    deleted: false,
    salutationName: null,
    firstName: "Joan",
    lastName: "Huang",
    title: null,
    description: "Online Resume: https://jojoxo.web.app/index.html",
    doNotCall: false,
    accountIsInactive: null,
    accountType: null,
    createdAt: "2024-02-12 20:50:01",
    modifiedAt: "2024-02-21 21:32:41",
    hasPortalUser: false,
    skills: [
      "css",
      "figma",
      "frontend",
      "html",
      "javascript",
      "laravel",
      "php",
      "react",
      "sql",
      "vue",
      "wordpress",
    ],
    type: "Candidate / Member",
    publicDescription: null,
    publicLink: null,
    middleName: null,
    accountId: null,
    accountName: null,
    campaignId: null,
    campaignName: null,
    createdById: "6583041ddb944e569",
    createdByName: "Sam Simonds",
    modifiedById: "6583041ddb944e569",
    modifiedByName: "Sam Simonds",
    assignedUserId: null,
    assignedUserName: null,
    portalUserId: null,
    portalUserName: null,
    originalLeadId: null,
    originalLeadName: null,
    publicPhotoId: null,
    publicPhotoName: null,
  },
  {
    id: "65ca82f9a6fd2f83d",
    name: "Jim Lan",
    deleted: false,
    salutationName: null,
    firstName: "Jim",
    lastName: "Lan",
    title: null,
    description: null,
    doNotCall: false,
    accountIsInactive: null,
    accountType: null,
    createdAt: "2024-02-12 20:43:37",
    modifiedAt: "2024-02-21 21:33:07",
    hasPortalUser: false,
    skills: ["firmware dev", "tr/tx", "wfa tgn/tgac", "wifi"],
    type: "Candidate / Member",
    publicDescription: null,
    publicLink: null,
    middleName: null,
    accountId: null,
    accountName: null,
    campaignId: null,
    campaignName: null,
    createdById: "6583041ddb944e569",
    createdByName: "Sam Simonds",
    modifiedById: "6583041ddb944e569",
    modifiedByName: "Sam Simonds",
    assignedUserId: null,
    assignedUserName: null,
    portalUserId: null,
    portalUserName: null,
    originalLeadId: null,
    originalLeadName: null,
    publicPhotoId: null,
    publicPhotoName: null,
  },
  {
    id: "65ca81e23b79af177",
    name: "Richard Lee",
    deleted: false,
    salutationName: null,
    firstName: "Richard",
    lastName: "Lee",
    title: null,
    description: null,
    doNotCall: false,
    accountIsInactive: null,
    accountType: null,
    createdAt: "2024-02-12 20:38:58",
    modifiedAt: "2024-02-21 21:34:02",
    hasPortalUser: false,
    skills: ["AI", "android", "java", "machine learning", "php", "python"],
    type: "Candidate / Member",
    publicDescription: null,
    publicLink: null,
    middleName: null,
    accountId: null,
    accountName: null,
    campaignId: null,
    campaignName: null,
    createdById: "6583041ddb944e569",
    createdByName: "Sam Simonds",
    modifiedById: "6583041ddb944e569",
    modifiedByName: "Sam Simonds",
    assignedUserId: null,
    assignedUserName: null,
    portalUserId: null,
    portalUserName: null,
    originalLeadId: null,
    originalLeadName: null,
    publicPhotoId: null,
    publicPhotoName: null,
  },
  {
    id: "65ca7faa8c089c70c",
    name: "Wilson Kao",
    deleted: false,
    salutationName: null,
    firstName: "Wilson",
    lastName: "Kao",
    title: null,
    description:
      "Updated resume link: https://www.cakeresume.com/s--H1Fps82FJOrXy5l6AzKibw--/wilson-kao-a402d7",
    doNotCall: false,
    accountIsInactive: null,
    accountType: null,
    createdAt: "2024-02-12 20:29:30",
    modifiedAt: "2024-02-21 21:35:34",
    hasPortalUser: false,
    skills: [
      "axios",
      "css",
      "firebase",
      "frontend",
      "git",
      "html",
      "javascript",
      "node",
      "pinia",
      "python",
      "restful api",
      "tailwind",
      "typescript",
      "vue",
    ],
    type: "Candidate / Member",
    publicDescription: null,
    publicLink: null,
    middleName: null,
    accountId: null,
    accountName: null,
    campaignId: null,
    campaignName: null,
    createdById: "6583041ddb944e569",
    createdByName: "Sam Simonds",
    modifiedById: "6583041ddb944e569",
    modifiedByName: "Sam Simonds",
    assignedUserId: null,
    assignedUserName: null,
    portalUserId: null,
    portalUserName: null,
    originalLeadId: null,
    originalLeadName: null,
    publicPhotoId: null,
    publicPhotoName: null,
  },
  {
    id: "65c57415528ed25b3",
    name: "Henry Chang",
    deleted: false,
    salutationName: null,
    firstName: "Henry",
    lastName: "Chang",
    title: null,
    description: null,
    doNotCall: false,
    accountIsInactive: null,
    accountType: null,
    createdAt: "2024-02-09 00:38:45",
    modifiedAt: "2024-02-26 03:32:27",
    hasPortalUser: false,
    skills: ["backend", "python"],
    type: "Candidate / Member",
    publicDescription: null,
    publicLink: null,
    middleName: null,
    accountId: null,
    accountName: null,
    campaignId: null,
    campaignName: null,
    createdById: "65a5d89c1b887d3f6",
    createdByName: "Nestor Morales",
    modifiedById: "6583041ddb944e569",
    modifiedByName: "Sam Simonds",
    assignedUserId: null,
    assignedUserName: null,
    portalUserId: null,
    portalUserName: null,
    originalLeadId: null,
    originalLeadName: null,
    publicPhotoId: null,
    publicPhotoName: null,
  },
];
